### ISSUE TITLE
GameControl UI: figure out a good way to map keyboard buttons to GameControl buttons

### ISSUE THREAD

**Issue by AndrewMeadows** [secondlife/viewer#1363]
The primary goal of the **GameControl** feature is to expose input from a client-side game controller to server-side LSL scripts, however not all SL users will have a game controller and we would like to make it possible for "keyboardists" to supply **GameControl** input to in-world content.  This gets a little tricky because:

**1.** Most of the obvious candidate keys are already mapped to something.
**2.** There is functional overlap between controlling the avatar with keyboard, controlling avatar with game controller, and collecting input for sending to server.

At the moment an equivalency can be configured between "avatar control" input (e.g. key presses, or mouse-clicks on **Walk/Run/Fly** UI floater) and **GameControl** input.  When enabled: pressing the "walk forward" key can be translated to a **GameControl Axis** being set to **+1.0**.  **Me-menu --> Preferences...-option --> Game_Control-tab --> Action_table**.  This works ok for an **Axis** although it doesn't allow for floating point values.

But what to do for **GameControl Buttons**?

One idea which was tried but doesn't work well is to map other avatar actions to **Buttons**: e.g. "toggle fly" maps to **Button9**.

Another idea to try is to add new rows to the key mapping UI: **Me-menu --> Controls --> Action-table**. The new rows would be **GameControl_Button_00** to **Button_31**.  These need to be in the **Controls** UI because that is where all the key mappings are listed and where mapping conflicts are resolved in the UI logic.  With some effort these key mappings could also be configured in the **Game_Control-tab**, but that work should probably be done later after prototyping.

**Comment by AndrewMeadows** [comment]
Work is being done in **leviathan/game-control** branch.

**Comment by AndrewMeadows** [comment]
This is basically done.  GameControl **BUTTON_0** through **BUTTON_31** have been added at the bottom of the keyboard map table (**Me-menu --> Preferences...-option --> Controls-tab --> Actions-table**) and keys can be mapped to that input.

The GameControl Axes are not mapped there.  Instead avatar movement actions (e.g. push_forward, slide_left, etc) are mapped in the Game_Control UI (**Me-menu --> Preferences...-option --> Game_Control-tab --> Actions-table**).

**Comment by tapple** [comment]
I tried this viewer today on fedora linux: Second Life Project Game-control 7.2.3.21405527441 (64bit)

Every time I pressed ok in the Control tab from setting up some keyboard mappings, all my settings are gone next time I re-open the window:

<img width="835" height="684" alt="Image" src="https://github.com/user-attachments/assets/7cb8945c-4df9-4878-8dd5-2fc56e8853d5" />

Press ok, then re-open: settings gone:

<img width="835" height="684" alt="Image" src="https://github.com/user-attachments/assets/bb12eff3-cd2c-4c6a-86bb-5594338aba34" />

**Comment by AndrewMeadows** [comment]
@tapple the problem where the remapping of avatar actions to game controller input channels would not save is fixed in pre-release [v0.7.1](https://github.com/secondlife/viewer/releases/tag/Second_Life_Project_game_control-0.7.1).  I forgot to open a new github issue for it because it was being reported in this one.

**Comment by tapple** [comment]
I tried viewer `Second Life Project Game-control 7.2.3.22658745336 (64bit)` from your link (on fedora linux), and custom controls still vanish when I close and re-open the preferences. maybe I should try it from fresh settings

EDIT: It didn't help:
1. I renamed `~/.secondlife` to start fresh
2. I logged in, enabled advanced menu, enabled debug setting `EnableGameControl`.
3. I relogged, went to preferences > controls, and set BUTTON_0 PrimaryControl to "1", `BUTTON_1` to "2", etc
4. I closed and re-opened preferences > controls. No custom keybindings visible on BUTTON_0 or others

**Comment by tapple** [comment]
@AndrewMeadows I also tried on windows, in case linux was doing something weird. Still not fixed on windows either
